server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  #Grafana Lokiのサーバーアドレスを入れる
  - url: http://${SERVER_ADDR}:3100/loki/api/v1/push

scrape_configs:
  - job_name: varlogs
    static_configs:
    - targets:
        - localhost
      labels:
        #ホスト名を入れる
        host: ${HOSTNAME}
        job: varlogs
        __path__: /promtail/log/**/*.log
  - job_name: journal
    journal:
      json: false
      max_age: 12h
      path: /promtail/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
    - source_labels:
      - __journal__hostname
      target_label: host
    - source_labels:
      - __journal__systemd_unit
      target_label: systemd_unit
    - source_labels:
      - __journal_priority_keyword
      target_label: level